const countryData = {
  Afghanistan: { code: "af", label: "Afghanistan" },
  Albania: { code: "al", label: "Albania" },
  Algeria: { code: "dz", label: "Algeria" },
  Andorra: { code: "ad", label: "Andorra" },
  Angola: { code: "ao", label: "Angola" },
  AntiguaAndBarbuda: { code: "ag", label: "Antigua and Barbuda" },
  Argentina: { code: "ar", label: "Argentina" },
  Armenia: { code: "am", label: "Armenia" },
  Australia: { code: "au", label: "Australia" },
  Austria: { code: "at", label: "Austria" },
  Azerbaijan: { code: "az", label: "Azerbaijan" },
  Bahamas: { code: "bs", label: "Bahamas" },
  Bahrain: { code: "bh", label: "Bahrain" },
  Bangladesh: { code: "bd", label: "Bangladesh" },
  Barbados: { code: "bb", label: "Barbados" },
  Belarus: { code: "by", label: "Belarus" },
  Belgium: { code: "be", label: "Belgium" },
  Belize: { code: "bz", label: "Belize" },
  Benin: { code: "bj", label: "Benin" },
  Bhutan: { code: "bt", label: "Bhutan" },
  Bolivia: { code: "bo", label: "Bolivia" },
  BosniaAndHerzegovina: { code: "ba", label: "Bosnia and Herzegovina" },
  Botswana: { code: "bw", label: "Botswana" },
  Brazil: { code: "br", label: "Brazil" },
  Brunei: { code: "bn", label: "Brunei" },
  Bulgaria: { code: "bg", label: "Bulgaria" },
  BurkinaFaso: { code: "bf", label: "Burkina Faso" },
  Burundi: { code: "bi", label: "Burundi" },
  Cambodia: { code: "kh", label: "Cambodia" },
  Cameroon: { code: "cm", label: "Cameroon" },
  Canada: { code: "ca", label: "Canada" },
  CapeVerde: { code: "cv", label: "Cape Verde" },
  CentralAfricanRepublic: { code: "cf", label: "Central African Republic" },
  Chad: { code: "td", label: "Chad" },
  Chile: { code: "cl", label: "Chile" },
  China: { code: "cn", label: "China" },
  Colombia: { code: "co", label: "Colombia" },
  Comoros: { code: "km", label: "Comoros" },
  CostaRica: { code: "cr", label: "Costa Rica" },
  Croatia: { code: "hr", label: "Croatia" },
  Cuba: { code: "cu", label: "Cuba" },
  Cyprus: { code: "cy", label: "Cyprus" },
  CzechRepublic: { code: "cz", label: "Czech Republic" },
  Denmark: { code: "dk", label: "Denmark" },
  Djibouti: { code: "dj", label: "Djibouti" },
  Dominica: { code: "dm", label: "Dominica" },
  DominicanRepublic: { code: "do", label: "Dominican Republic" },
  Ecuador: { code: "ec", label: "Ecuador" },
  Egypt: { code: "eg", label: "Egypt" },
  ElSalvador: { code: "sv", label: "El Salvador" },
  EquatorialGuinea: { code: "gq", label: "Equatorial Guinea" },
  Eritrea: { code: "er", label: "Eritrea" },
  Estonia: { code: "ee", label: "Estonia" },
  Eswatini: { code: "sz", label: "Eswatini" },
  Ethiopia: { code: "et", label: "Ethiopia" },
  Fiji: { code: "fj", label: "Fiji" },
  Finland: { code: "fi", label: "Finland" },
  France: { code: "fr", label: "France" },
  Gabon: { code: "ga", label: "Gabon" },
  Gambia: { code: "gm", label: "Gambia" },
  Georgia: { code: "ge", label: "Georgia" },
  Germany: { code: "de", label: "Germany" },
  Ghana: { code: "gh", label: "Ghana" },
  Greece: { code: "gr", label: "Greece" },
  Grenada: { code: "gd", label: "Grenada" },
  Guatemala: { code: "gt", label: "Guatemala" },
  Guinea: { code: "gn", label: "Guinea" },
  Guyana: { code: "gy", label: "Guyana" },
  Haiti: { code: "ht", label: "Haiti" },
  Honduras: { code: "hn", label: "Honduras" },
  Hungary: { code: "hu", label: "Hungary" },
  Iceland: { code: "is", label: "Iceland" },
  India: { code: "in", label: "India" },
  Indonesia: { code: "id", label: "Indonesia" },
  Iran: { code: "ir", label: "Iran" },
  Iraq: { code: "iq", label: "Iraq" },
  Ireland: { code: "ie", label: "Ireland" },
  Israel: { code: "il", label: "Israel" },
  Italy: { code: "it", label: "Italy" },
  Jamaica: { code: "jm", label: "Jamaica" },
  Japan: { code: "jp", label: "Japan" },
  Jordan: { code: "jo", label: "Jordan" },
  Kazakhstan: { code: "kz", label: "Kazakhstan" },
  Kenya: { code: "ke", label: "Kenya" },
  Kuwait: { code: "kw", label: "Kuwait" },
  Kyrgyzstan: { code: "kg", label: "Kyrgyzstan" },
  Laos: { code: "la", label: "Laos" },
  Latvia: { code: "lv", label: "Latvia" },
  Lebanon: { code: "lb", label: "Lebanon" },
  Liberia: { code: "lr", label: "Liberia" },
  Libya: { code: "ly", label: "Libya" },
  Lithuania: { code: "lt", label: "Lithuania" },
  Luxembourg: { code: "lu", label: "Luxembourg" },
  Madagascar: { code: "mg", label: "Madagascar" },
  Malawi: { code: "mw", label: "Malawi" },
  Malaysia: { code: "my", label: "Malaysia" },
  Maldives: { code: "mv", label: "Maldives" },
  Mali: { code: "ml", label: "Mali" },
  Malta: { code: "mt", label: "Malta" },
  Mauritius: { code: "mu", label: "Mauritius" },
  Mexico: { code: "mx", label: "Mexico" },
  Mongolia: { code: "mn", label: "Mongolia" },
  Montenegro: { code: "me", label: "Montenegro" },
  Morocco: { code: "ma", label: "Morocco" },
  Mozambique: { code: "mz", label: "Mozambique" },
  Myanmar: { code: "mm", label: "Myanmar" },
  Namibia: { code: "na", label: "Namibia" },
  Nepal: { code: "np", label: "Nepal" },
  Netherlands: { code: "nl", label: "Netherlands" },
  NewZealand: { code: "nz", label: "New Zealand" },
  Nigeria: { code: "ng", label: "Nigeria" },
  Norway: { code: "no", label: "Norway" },
  Oman: { code: "om", label: "Oman" },
  Pakistan: { code: "pk", label: "Pakistan" },
  Panama: { code: "pa", label: "Panama" },
  PapuaNewGuinea: { code: "pg", label: "Papua New Guinea" },
  Paraguay: { code: "py", label: "Paraguay" },
  Peru: { code: "pe", label: "Peru" },
  Philippines: { code: "ph", label: "Philippines" },
  Poland: { code: "pl", label: "Poland" },
  Portugal: { code: "pt", label: "Portugal" },
  Qatar: { code: "qa", label: "Qatar" },
  Romania: { code: "ro", label: "Romania" },
  Russia: { code: "ru", label: "Russia" },
  SaudiArabia: { code: "sa", label: "Saudi Arabia" },
  Serbia: { code: "rs", label: "Serbia" },
  Singapore: { code: "sg", label: "Singapore" },
  Slovakia: { code: "sk", label: "Slovakia" },
  Slovenia: { code: "si", label: "Slovenia" },
  SouthAfrica: { code: "za", label: "South Africa" },
  SouthKorea: { code: "kr", label: "South Korea" },
  Spain: { code: "es", label: "Spain" },
  SriLanka: { code: "lk", label: "Sri Lanka" },
  Sweden: { code: "se", label: "Sweden" },
  Switzerland: { code: "ch", label: "Switzerland" },
  Taiwan: { code: "tw", label: "Taiwan" },
  Thailand: { code: "th", label: "Thailand" },
  Turkey: { code: "tr", label: "Turkey" },
  UAE: { code: "ae", label: "United Arab Emirates" },
  UK: { code: "gb", label: "United Kingdom" },
  USA: { code: "us", label: "United States" },
  Uruguay: { code: "uy", label: "Uruguay" },
  Uzbekistan: { code: "uz", label: "Uzbekistan" },
  Venezuela: { code: "ve", label: "Venezuela" },
  Vietnam: { code: "vn", label: "Vietnam" },
  Yemen: { code: "ye", label: "Yemen" },
  Zambia: { code: "zm", label: "Zambia" },
  Zimbabwe: { code: "zw", label: "Zimbabwe" },
};

export default function CountryFlag({ country }) {
  const data = countryData[country];

  if (!data) {
    return (
      <div className="flex items-center gap-2">
        <span>🌍</span>
        <span>{country}</span>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2">
      <img
        src={`https://flagcdn.com/w40/${data.code}.png`}
        alt={data.label}
        className="w-6 h-4 object-cover rounded-sm"
      />
      <span className="text-sm font-medium text-slate-700">
        {data.label}
      </span>
    </div>
  );
}